// Switch to netflixdb
db = db.getSiblingDB('netflixdb');

db.movies.insertMany([
  {
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
    genre: ["Sci-Fi", "Horror", "Drama"],
    rating: 8.7,
    year: 2016,
    duration: "50 min/ep",
    type: "series",
    category: "trending",
    thumbnail: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=1280&q=80",
    featured: true,
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "David Harbour"],
    language: "English",
    maturityRating: "TV-14"
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    year: 2008,
    duration: "152 min",
    type: "movie",
    category: "trending",
    thumbnail: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1280&q=80",
    featured: false,
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    language: "English",
    maturityRating: "PG-13"
  },
  {
    title: "Money Heist",
    description: "A criminal mastermind who goes by 'The Professor' has a plan to pull off the biggest heist in recorded history — to print billions of euros in the Royal Mint of Spain.",
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.2,
    year: 2017,
    duration: "45 min/ep",
    type: "series",
    category: "popular",
    thumbnail: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=1280&q=80",
    featured: false,
    cast: ["Álvaro Morte", "Itziar Ituño", "Pedro Alonso"],
    language: "Spanish",
    maturityRating: "TV-MA"
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.8,
    year: 2010,
    duration: "148 min",
    type: "movie",
    category: "popular",
    thumbnail: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1280&q=80",
    featured: false,
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    language: "English",
    maturityRating: "PG-13"
  },
  {
    title: "Breaking Bad",
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family's future.",
    genre: ["Crime", "Drama", "Thriller"],
    rating: 9.5,
    year: 2008,
    duration: "47 min/ep",
    type: "series",
    category: "trending",
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1280&q=80",
    featured: false,
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    language: "English",
    maturityRating: "TV-MA"
  },
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    year: 2014,
    duration: "169 min",
    type: "movie",
    category: "new",
    thumbnail: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1280&q=80",
    featured: false,
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    language: "English",
    maturityRating: "PG-13"
  },
  {
    title: "The Crown",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
    genre: ["Biography", "Drama", "History"],
    rating: 8.6,
    year: 2016,
    duration: "58 min/ep",
    type: "series",
    category: "new",
    thumbnail: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1280&q=80",
    featured: false,
    cast: ["Olivia Colman", "Tobias Menzies", "Helena Bonham Carter"],
    language: "English",
    maturityRating: "TV-MA"
  },
  {
    title: "Avengers: Endgame",
    description: "After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos' actions.",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.4,
    year: 2019,
    duration: "181 min",
    type: "movie",
    category: "popular",
    thumbnail: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=1280&q=80",
    featured: false,
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    language: "English",
    maturityRating: "PG-13"
  },
  {
    title: "Dark",
    description: "A missing child sets four interconnected families on a frantic hunt for answers as they unearth a sinister time travel conspiracy spanning several generations.",
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.8,
    year: 2017,
    duration: "60 min/ep",
    type: "series",
    category: "new",
    thumbnail: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1280&q=80",
    featured: false,
    cast: ["Louis Hofmann", "Oliver Masucci", "Jördis Triebel"],
    language: "German",
    maturityRating: "TV-MA"
  },
  {
    title: "The Witcher",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    genre: ["Action", "Adventure", "Fantasy"],
    rating: 8.2,
    year: 2019,
    duration: "60 min/ep",
    type: "series",
    category: "trending",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1280&q=80",
    featured: false,
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
    language: "English",
    maturityRating: "TV-MA"
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    genre: ["Comedy", "Drama", "Thriller"],
    rating: 8.6,
    year: 2019,
    duration: "132 min",
    type: "movie",
    category: "popular",
    thumbnail: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1280&q=80",
    featured: false,
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    language: "Korean",
    maturityRating: "R"
  },
  {
    title: "Squid Game",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    genre: ["Action", "Drama", "Mystery"],
    rating: 8.0,
    year: 2021,
    duration: "54 min/ep",
    type: "series",
    category: "trending",
    thumbnail: "https://images.unsplash.com/photo-1614729939124-032d1e6c9945?w=500&q=80",
    backdrop: "https://images.unsplash.com/photo-1614729939124-032d1e6c9945?w=1280&q=80",
    featured: false,
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-jun"],
    language: "Korean",
    maturityRating: "TV-MA"
  }
]);

db.users.insertOne({
  name: "Demo User",
  email: "demo@netflix.com",
  password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy", // password: demo123
  plan: "premium",
  avatar: "D",
  myList: [],
  createdAt: new Date()
});

print("✅ Netflix DB seeded successfully!");
