name: code Quality

on:
    workflow_call:

jobs:
   Code Quality:
    runs-on: ubuntu-latest

    steps:

        

        - name: Testing
          run: |
            echo "Kya haal hai"