name: Frontend code linting

on:
  workflow_call:
  workflow_dispatch:

jobs:
   Code_Quality:
    runs-on: ubuntu-latest

    steps:

        - name: Code Checkout
          uses: actions/checkout@v6
        

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 25
        - run: npm ci
        - run: npm test
        