name: Frontend code linting

on:
  workflow_call:
  workflow_dispatch:

jobs:
   Code_Quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:

        - name: Code Checkout
          uses: actions/checkout@v6
        

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 25

        - name: Install Dependencies
          run: npm install

        - name: Check HTML
          run: npx htmlhint "public/**/*.html"

        - name: Check CSS
          run: npx stylelint "public/css/**/*.css"

        - name: Check JS
          run: npx eslint "public/js/**/*.js"

        
