name: code Quality

on:
  workflow_call:
  workflow_dispatch:

jobs:
   Code_Quality:
    runs-on: ubuntu-latest

    steps:

        - name: Code Checkout
          uses: actions/checkout@v4

        - name: Testing
          run: |
            echo "Kya haal hai"