name: Secrets Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
    Secrets_Scan:
        runs-on: ubuntu-latest

        steps:

            - name: Code Checkout
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN:  ${{ secrets.TOKEN_GITHUB }}
